spring.application.name: auth-registration-service
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql}

  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
      format-sql: true
      use_sql_comments: false
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    clean-on-validation-error: true
    validate-on-migrate: true

logging:
  file:
    name: logs/app.log  # Путь к файлу логов
  level:
    root: INFO
