CREATE TABLE users(
	user_id INt GENERATED ALWAYS AS IDENTITY NOT NULL PRIMARY KEY,
	user_login VARCHAR(20) NOT NULL UNIQUE,
	user_mail VARCHAR(40) UNIQUE,
	user_password VARCHAR(20) NOT NULL,
	role VARCHAR(20) NOT NULL
);